// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CaptureSource is a user-selected audio device and the role its audio plays.
 */
export interface CaptureSource {
    /**
     * device hex token; "" = default
     */
    "id": string;

    /**
     * display name
     */
    "name": string;

    /**
     * "input" | "loopback"
     */
    "kind": string;

    /**
     * "You" | "Others" | "Room"
     */
    "label": string;
}

/**
 * Profile is reusable context the user supplies to ground the analysis.
 */
export interface Profile {
    "id": number;
    "name": string;
    "summary": string;
    "people": string;
    "notes": string;
    "updatedAt": string;
}

/**
 * Settings holds app-wide configuration (the API key is never included here).
 */
export interface Settings {
    "llmBaseURL": string;
    "llmModel": string;
    "analysisIntervalSec": number;
    "activeProfileID": number;
    "hasAPIKey": boolean;
    "captureSources": CaptureSource[] | null;
}
