// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CaptureSource is a user-selected audio device and the role its audio plays.
 */
export interface CaptureSource {
    /**
     * device hex token; "" = default
     */
    "id": string;

    /**
     * display name
     */
    "name": string;

    /**
     * "input" | "loopback"
     */
    "kind": string;

    /**
     * "You" | "Others" | "Room"
     */
    "label": string;
}

/**
 * LiveNote is a piece of context the user injects mid-meeting. A "meeting"-scoped
 * note applies for the whole session (names, themes); a "topic"-scoped note only
 * applies while its topic is current and expires when the topic rolls over.
 */
export interface LiveNote {
    "id": number;

    /**
     * "meeting" | "topic"
     */
    "scope": string;

    /**
     * topic active when a "topic" note was added
     */
    "topicTitle": string;
    "text": string;
    "createdAt": string;
}

/**
 * LLMConnection is a saved, named LLM endpoint the user can switch between.
 * The API key is kept in the OS keychain, never in this struct.
 */
export interface LLMConnection {
    "id": number;
    "name": string;
    "baseURL": string;
    "model": string;
    "hasAPIKey": boolean;
    "updatedAt": string;
}

/**
 * Profile is reusable context the user supplies to ground the analysis.
 */
export interface Profile {
    "id": number;
    "name": string;
    "summary": string;
    "people": string;
    "notes": string;
    "updatedAt": string;
}

/**
 * Session is a (possibly multi-part) recorded meeting.
 */
export interface Session {
    "id": number;
    "title": string;
    "startedAt": string;
    "endedAt": string;
    "profileID": number;
    "audioDir": string;

    /**
     * populated by ListSessions for the browser
     */
    "segmentCount": number;
}

/**
 * Settings holds app-wide configuration (the API key is never included here).
 */
export interface Settings {
    "llmBaseURL": string;
    "llmModel": string;
    "analysisIntervalSec": number;
    "activeProfileID": number;
    "hasAPIKey": boolean;
    "captureSources": CaptureSource[] | null;

    /**
     * SttBaseURL, when set, points transcription at a remote whisper.cpp-compatible
     * server (e.g. http://host:8765) instead of launching the bundled engine.
     */
    "sttBaseURL": string;

    /**
     * WhisperModel is the model filename under resources/whisper/models used by the
     * bundled engine. A small model (e.g. ggml-base.en.bin) keeps CPU use light.
     */
    "whisperModel": string;

    /**
     * ActiveLLMConnectionID selects which saved LLM connection drives analysis.
     */
    "activeLLMConnectionID": number;
}
