// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../tomvokac/parley/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as analysis$0 from "../../../../tomvokac/parley/internal/analysis/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as stt$0 from "../../../../tomvokac/parley/internal/stt/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "analysis": analysis$0.State;
            "analysisStatus": main$0.AnalysisStatusEvent;
            "runtimeInfo": main$0.RuntimeInfo;
            "status": main$0.StatusEvent;
            "transcript": stt$0.Segment;
        }
    }
}
