// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audio$0 from "../audio/models.js";

/**
 * Segment is a transcribed slice of one source's audio.
 */
export interface Segment {
    "source": audio$0.Source;
    "text": string;
    "startMs": number;
    "endMs": number;
}
