// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes settings and context-profile management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * DeleteProfile removes a context profile.
 */
export function DeleteProfile(id: number): $CancellablePromise<void> {
    return $Call.ByID(2338248010, id);
}

/**
 * GetSettings returns persisted settings (HasAPIKey indicates a stored key).
 */
export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(4146263007);
}

/**
 * ListProfiles returns all saved context profiles.
 */
export function ListProfiles(): $CancellablePromise<store$0.Profile[] | null> {
    return $Call.ByID(3577742188);
}

/**
 * SaveProfile inserts or updates a context profile.
 */
export function SaveProfile(p: store$0.Profile): $CancellablePromise<store$0.Profile> {
    return $Call.ByID(2808080692, p);
}

/**
 * SaveSettings persists settings (excluding the API key).
 */
export function SaveSettings(s: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1950234102, s);
}

/**
 * SetAPIKey stores or clears the LLM API key in the OS keychain.
 */
export function SetAPIKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(1925164905, key);
}

/**
 * TestConnection verifies the configured LLM endpoint/model/key respond.
 */
export function TestConnection(): $CancellablePromise<void> {
    return $Call.ByID(3263505778);
}
