// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MeetingService is the Wails-bound façade that drives capture + transcription.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audio$0 from "./internal/audio/models.js";

/**
 * IsRunning reports whether a session is active.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1753155539);
}

/**
 * ListDevices enumerates all audio devices (inputs and outputs) with stable IDs.
 */
export function ListDevices(): $CancellablePromise<audio$0.DeviceInfo[] | null> {
    return $Call.ByID(1850356551);
}

/**
 * Start launches the whisper server, begins capture, and starts transcribing.
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(4124033072);
}

/**
 * Stop ends the session, flushing the final audio and closing recordings.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(252224180);
}
