// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MeetingService is the Wails-bound façade that drives capture + transcription.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audio$0 from "./internal/audio/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLiveNote injects user context mid-meeting. scope is "meeting" (whole
 * session) or "topic" (current topic only); it is fed to the analysis engine and
 * persisted with the session.
 */
export function AddLiveNote(scope: string, text: string): $CancellablePromise<store$0.LiveNote> {
    return $Call.ByID(1344950533, scope, text);
}

/**
 * ConfigureTranscription validates and persists a model selection, then
 * reconciles the idle runtime. Local loading continues asynchronously.
 */
export function ConfigureTranscription(config: $models.TranscriptionConfig): $CancellablePromise<void> {
    return $Call.ByID(713856948, config);
}

/**
 * DeleteSession permanently removes a saved meeting (not the one in progress).
 */
export function DeleteSession(id: number): $CancellablePromise<void> {
    return $Call.ByID(4268697921, id);
}

/**
 * ExportMarkdown saves the active or selected meeting's notes as a Markdown file.
 * Pass sessionID=0 to export the currently running session.
 */
export function ExportMarkdown(sessionID: number): $CancellablePromise<string> {
    return $Call.ByID(3378443135, sessionID);
}

/**
 * ExportTranscriptMarkdown saves the exact pre-meeting context snapshot followed
 * by the complete persisted transcript. It intentionally excludes analysis and
 * live notes.
 */
export function ExportTranscriptMarkdown(sessionID: number): $CancellablePromise<string> {
    return $Call.ByID(1564234185, sessionID);
}

/**
 * GetRuntimeInfo reports the exact app version and the transcription model that
 * has actually been selected. In particular, this reflects a CPU fallback when
 * Nemotron was preferred but could not start, rather than merely echoing the
 * configured model filename.
 */
export function GetRuntimeInfo(): $CancellablePromise<$models.RuntimeInfo> {
    return $Call.ByID(3989995776);
}

/**
 * IsRunning reports whether a session is active.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1753155539);
}

/**
 * ListDevices enumerates all audio devices (inputs and outputs) with stable IDs.
 */
export function ListDevices(): $CancellablePromise<audio$0.DeviceInfo[] | null> {
    return $Call.ByID(1850356551);
}

/**
 * ListSessions returns saved meetings, newest first.
 */
export function ListSessions(): $CancellablePromise<store$0.Session[] | null> {
    return $Call.ByID(1774945289);
}

/**
 * ListTranscriptionModels discovers the selectable local installations and the
 * always-available external-server choice.
 */
export function ListTranscriptionModels(): $CancellablePromise<$models.TranscriptionModelOption[] | null> {
    return $Call.ByID(1026157818);
}

/**
 * LoadSession returns a saved meeting's full state for display.
 */
export function LoadSession(id: number): $CancellablePromise<$models.LoadedSession> {
    return $Call.ByID(1403894156, id);
}

/**
 * RenameSession changes a saved meeting's title.
 */
export function RenameSession(id: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(3925232594, id, title);
}

/**
 * RestartTranscriptionModel replaces the current local process with a fresh load.
 */
export function RestartTranscriptionModel(): $CancellablePromise<void> {
    return $Call.ByID(3040477430);
}

/**
 * Resume continues a previously saved meeting, appending new transcript/analysis
 * to it. Pass the session id returned by ListSessions.
 */
export function Resume(id: number): $CancellablePromise<void> {
    return $Call.ByID(2982998431, id);
}

/**
 * Start launches a fresh meeting using the app's preloaded transcription engine,
 * then starts capture and a new persisted session.
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(4124033072);
}

/**
 * StartTranscriptionModel loads the selected local model without starting a meeting.
 */
export function StartTranscriptionModel(): $CancellablePromise<void> {
    return $Call.ByID(2331669113);
}

/**
 * Stop ends the session, flushing the final audio and closing recordings.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(252224180);
}

/**
 * StopTranscriptionModel releases the selected local model while Parley is idle.
 */
export function StopTranscriptionModel(): $CancellablePromise<void> {
    return $Call.ByID(207813981);
}

/**
 * TestExternalTranscription verifies that an external HTTP server is reachable.
 * Any HTTP response counts as reachable; the inference path is exercised by the
 * first real transcription request.
 */
export function TestExternalTranscription(baseURL: string): $CancellablePromise<void> {
    return $Call.ByID(1170675977, baseURL);
}
