// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatusEvent is broadcast whenever the capture/transcription state changes.
 */
export interface StatusEvent {
    /**
     * idle | starting | listening | error
     */
    "state": string;
    "message": string;
    "micAvailable": boolean;
    "activeSources": string[] | null;
}
