// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as analysis$0 from "./internal/analysis/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stt$0 from "./internal/stt/models.js";

/**
 * LoadedSession is a saved meeting's full state, returned to the frontend so it
 * can repopulate the transcript and analysis panels (read-only view or resume).
 */
export interface LoadedSession {
    "session": store$0.Session;
    "segments": stt$0.Segment[] | null;
    "analysis": analysis$0.State;
    "liveNotes": store$0.LiveNote[] | null;
}

/**
 * StatusEvent is broadcast whenever the capture/transcription state changes.
 */
export interface StatusEvent {
    /**
     * idle | starting | listening | error
     */
    "state": string;
    "message": string;
    "micAvailable": boolean;
    "activeSources": string[] | null;
}
