// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionItem is a task/follow-up surfaced during the meeting, optionally owned by
 * someone. Unlike Assertion, action items are meeting-level: they accumulate for
 * the whole session and survive topic changes.
 */
export interface ActionItem {
    "text": string;

    /**
     * "" when no owner was stated
     */
    "owner": string;
}

/**
 * Assertion is a point/claim made on a topic, attributed to a speaker.
 */
export interface Assertion {
    "speaker": string;
    "text": string;
}

/**
 * State is the full analysis snapshot pushed to the UI.
 */
export interface State {
    "current": Topic;
    "past": Topic[] | null;
    "suggestions": Suggestion[] | null;

    /**
     * ActionItems are meeting-level: they accumulate across the whole session and
     * are not tied to (or cleared with) the current topic.
     */
    "actionItems": ActionItem[] | null;
}

/**
 * Suggestion is a question or clarification the listener could raise now.
 */
export interface Suggestion {
    /**
     * "question" | "clarification"
     */
    "kind": string;
    "text": string;
}

/**
 * Topic groups a title, a short summary, and the assertions made about it.
 */
export interface Topic {
    "title": string;
    "summary": string;
    "assertions": Assertion[] | null;
}
