// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Assertion is a point/claim made on a topic, attributed to a speaker.
 */
export interface Assertion {
    "speaker": string;
    "text": string;
}

/**
 * State is the full analysis snapshot pushed to the UI.
 */
export interface State {
    "current": Topic;
    "past": Topic[] | null;
    "suggestions": Suggestion[] | null;
}

/**
 * Suggestion is a question or clarification the listener could raise now.
 */
export interface Suggestion {
    /**
     * "question" | "clarification"
     */
    "kind": string;
    "text": string;
}

/**
 * Topic groups a title, a short summary, and the assertions made about it.
 */
export interface Topic {
    "title": string;
    "summary": string;
    "assertions": Assertion[] | null;
}
