// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceInfo describes an enumerated audio device.
 */
export interface DeviceInfo {
    /**
     * hex token (stable per device); "" = system default
     */
    "id": string;
    "name": string;

    /**
     * "input" (capture) | "output" (playback)
     */
    "kind": string;
    "isDefault": boolean;
}

/**
 * Source is the transcript label applied to audio from a given capture source.
 */
export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * You is the local user's own microphone (attributable).
     */
    You = "You",

    /**
     * Others is remote/other participants (e.g. system loopback).
     */
    Others = "Others",

    /**
     * Room is an in-person/mixed capture where individual speakers — including
     * the user — cannot be separated.
     */
    Room = "Room",
};
